"""Legal document routes - serve Terms of Service and Privacy Policy."""

from __future__ import annotations

import re

from fastapi import APIRouter, Request
from fastapi.responses import HTMLResponse
from fastapi.templating import Jinja2Templates

templates = Jinja2Templates(directory="ortobahn/web/templates")

router = APIRouter(prefix="/legal")


def _markdown_to_html(text: str) -> str:
    """Convert basic markdown to HTML (headings, paragraphs, lists, bold, italic)."""
    lines = text.split("\n")
    html_parts: list[str] = []
    in_list = False

    for line in lines:
        stripped = line.strip()

        # Headings
        if stripped.startswith("### "):
            if in_list:
                html_parts.append("</ul>")
                in_list = False
            html_parts.append(f"<h3>{stripped[4:]}</h3>")
        elif stripped.startswith("## "):
            if in_list:
                html_parts.append("</ul>")
                in_list = False
            html_parts.append(f"<h2>{stripped[3:]}</h2>")
        elif stripped.startswith("# "):
            if in_list:
                html_parts.append("</ul>")
                in_list = False
            html_parts.append(f"<h1>{stripped[2:]}</h1>")
        # List items
        elif stripped.startswith("- ") or stripped.startswith("* "):
            if not in_list:
                html_parts.append("<ul>")
                in_list = True
            content = stripped[2:]
            content = re.sub(r"\*\*(.+?)\*\*", r"<strong>\1</strong>", content)
            content = re.sub(r"\*(.+?)\*", r"<em>\1</em>", content)
            html_parts.append(f"<li>{content}</li>")
        # Empty line
        elif not stripped:
            if in_list:
                html_parts.append("</ul>")
                in_list = False
        # Paragraph text
        else:
            if in_list:
                html_parts.append("</ul>")
                in_list = False
            content = stripped
            content = re.sub(r"\*\*(.+?)\*\*", r"<strong>\1</strong>", content)
            content = re.sub(r"\*(.+?)\*", r"<em>\1</em>", content)
            html_parts.append(f"<p>{content}</p>")

    if in_list:
        html_parts.append("</ul>")

    return "\n".join(html_parts)


def _render_legal_page(request: Request, doc: dict | None, doc_type: str, fallback_title: str) -> HTMLResponse:
    """Render a legal document page."""
    if doc:
        content_html = _markdown_to_html(doc["content"])
        return templates.TemplateResponse(
            "legal_page.html",
            {
                "request": request,
                "title": doc["title"],
                "content": content_html,
                "version": doc.get("version", ""),
                "effective_date": doc.get("effective_date", ""),
            },
        )
    return templates.TemplateResponse(
        "legal_page.html",
        {
            "request": request,
            "title": fallback_title,
            "content": "<p>This document is being generated by our Legal Agent and will be available shortly.</p>",
            "version": "",
            "effective_date": "",
        },
    )


@router.get("/terms", response_class=HTMLResponse)
async def terms_of_service(request: Request):
    """Serve the Terms of Service."""
    db = request.app.state.db
    doc = db.get_legal_document("terms_of_service")
    return _render_legal_page(request, doc, "terms_of_service", "Terms of Service")


@router.get("/privacy", response_class=HTMLResponse)
async def privacy_policy(request: Request):
    """Serve the Privacy Policy."""
    db = request.app.state.db
    doc = db.get_legal_document("privacy_policy")
    return _render_legal_page(request, doc, "privacy_policy", "Privacy Policy")
