"""Prompt tuner - analyzes performance data to generate strategy hints for the CEO agent."""

from __future__ import annotations

from ortobahn.db import Database


def get_performance_insights(db: Database, client_id: str | None = None) -> str:
    """Generate a performance insights string for the CEO agent.

    Analyzes recent posts by engagement to surface winning and losing patterns.
    Returns empty string if no data available.
    """
    posts = db.get_recent_posts_with_metrics(limit=50, client_id=client_id)
    if not posts:
        return ""

    # Calculate engagement per post
    for p in posts:
        p["engagement"] = (p.get("like_count") or 0) + (p.get("repost_count") or 0) + (p.get("reply_count") or 0)

    posts.sort(key=lambda p: p["engagement"], reverse=True)
    top = posts[:5]
    bottom = posts[-5:] if len(posts) >= 10 else []

    lines = ["## Performance Insights (auto-generated by PromptTuner)"]
    lines.append(f"Analyzed {len(posts)} recent published posts.\n")

    if top:
        lines.append("### Top Performing Posts:")
        for p in top:
            platform = p.get("platform", "unknown")
            lines.append(f"- [{p['engagement']} engagements, {platform}] {p['text'][:120]}...")

    if bottom:
        lines.append("\n### Lowest Performing Posts:")
        for p in bottom:
            platform = p.get("platform", "unknown")
            lines.append(f"- [{p['engagement']} engagements, {platform}] {p['text'][:120]}...")

    lines.append(
        "\nUse these patterns to inform strategy. Double down on what works. Avoid patterns from low performers."
    )
    return "\n".join(lines)
